language: php
php:
    - 5.6
    - 7
env:
    global:
        - CORE_BRANCH=master
        - APP_NAME=passman
    matrix:
        - DB=mysql

branches:
  only:
    - master


before_install:
    - export DISPLAY=:99.0
    - sh -e /etc/init.d/xvfb start
    - wget https://raw.githubusercontent.com/nextcloud/travis_ci/master/before_install.sh
    - bash ./before_install.sh $APP_NAME $CORE_BRANCH $DB
     # Add some output debugging information
    - cd ../server
    - ./occ check
    - ./occ status
    - ./occ app:list
    - ./occ user:add example --password-from-env
    - php -S localhost:8080 > /dev/null 2>&1 &
    - sleep 2
    - nvm install 5.9
    - npm install -g npm@latest
    - sh -c "if [ '$JSTESTS' = '1' ]; then npm install grunt-cli -g; fi"
    - sh -c "if [ '$PROTRAC' = '1' ]; then npm install protractor -g; fi"
    # sh -c "if [ '$PROTRAC' = '1' ]; then webdriver-manager update; fi"
    # sh -c "if [ '$PROTRAC' = '1' ]; then webdriver-manager start > /dev/null 2>&1 & fi"
    - sh -c "if [ '$PROTRAC' = '1' ]; then npm install jasmine-spec-reporter protractor@4.0.9; fi"


#
before_script:
    - ./occ app:enable passman

    - cd apps/$APP_NAME/
    - mkdir -p build
    - curl -sSL https://phar.phpunit.de/phpunit.phar -o build/phpunit.phar
    - sh -c "if [ '$JSTESTS' = '1' ]; then npm install; fi"



script:
    # Test the app
    - sh -c "if [ '$JSTESTS' != '1' -a '$CODECHECK' = '1' -a '$PROTRAC' != '1' ]; then find . -name \*.php -exec php -l \"{}\" \;; fi"
    - cd ../../
    - sh -c "if [ '$JSTESTS' != '1' -a '$CODECHECK' = '1' -a '$PROTRAC' != '1' ]; then ./occ app:check-code $APP_NAME -c private -c strong-comparison; fi"
    - sh -c "if [ '$JSTESTS' != '1' -a '$CODECHECK' = '2' -a '$PROTRAC' != '1' ]; then ./occ app:check-code $APP_NAME -c deprecation; fi"
    - cd apps/$APP_NAME/

    - sh -c "if [ '$JSTESTS' != '1' -a '$CODECHECK' != '1' -a '$CODECHECK' != '2' -a '$PROTRAC' != '1' ]; then php build/phpunit.phar -c phpunit.xml --coverage-clover clover.xml; fi"

    # Create coverage report
    - sh -c "if [ '$JSTESTS' != '1' -a '$CODECHECK' != '1' -a '$CODECHECK' != '2' -a '$PROTRAC' != '1' ]; then wget https://scrutinizer-ci.com/ocular.phar; fi"
    - sh -c "if [ '$JSTESTS' != '1' -a '$CODECHECK' != '1' -a '$CODECHECK' != '2' -a '$PROTRAC' != '1' ]; then php ocular.phar code-coverage:upload --format=php-clover clover.xml; fi"
    #- cd ../
    - sh -c "if [ '$JSTESTS' = '1' ]; then grunt jshint; fi"
    - sh -c "if [ '$PROTRAC' = '1' ]; then protractor .protractor.js; fi"

#after_failure:
#    - cat ../../data/owncloud.log

addons:
    sauce_connect: true

matrix:
  include:
    - php: 5.6
      env: DB=mysql;PROTRAC=1
    - php: 5.6
      env: DB=pgsql
    - php: 5.6
      env: DB=mysql;CODECHECK=1
    - php: 5.6
      env: DB=mysql;JSTESTS=1;
    - php: 7.0
      env: DB=mysql;CODECHECK=1
    - php: 5.6
      env: DB=mysql;CODECHECK=2
    - php: 7.0
      env: DB=mysql;CODECHECK=2
  allow_failures:
    - env: DB=mysql;CODECHECK=2